---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dingotiles/ghost-for-cloudfoundry-pipeline

inputs:
- name: ci
- name: develop
- name: master

outputs:
- name: merged

run:
  path: ci/ci/tasks/merge-master.sh
