---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dingotiles/ghost-for-cloudfoundry-pipeline

inputs:
- name: ci

params:
  route: https://ghost-for-cloudfoundry-ci.cfapps.io

run:
  path: ci/ci/tasks/sanity-test.sh
