---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dingotiles/ghost-for-cloudfoundry-pipeline

inputs:
- name: ci
- name: develop
- name: ghost

outputs:
- name: develop_upgraded

params:
  route: https://ghost-for-cloudfoundry-ci.cfapps.io

run:
  path: ci/ci/tasks/unpack-ghost-source.sh
