---
groups:
- name: pipeline
  jobs:
  - upgrade
- name: ci
  jobs:
  - build-task-image

jobs:
- name: upgrade
  public: true
  plan:
  - aggregate:
    - get: ghost-for-cf
    - get: ghost
      trigger: true
      params:
        drafts: false
        include_source_tarball: true
  - task: update-ghost-version
    file: ghost-for-cf/ci/tasks/update-ghost-version.yml

- name: build-task-image
  public: true
  serial: true
  plan:
  - get: ghost-for-cf-docker-image
    trigger: true
  - put: docker-image
    params:
      build: ghost-for-cf-docker-image/ci/ci_image

resources:
- name: ghost
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    user: TryGhost
    repository: ghost

- name: ghost-for-cf
  type: git
  source:
    uri: git@github.com:dingotiles/ghost-for-cloudfoundry.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}

- name: ghost-for-cf-docker-image
  type: git
  source:
    uri: git@github.com:dingotiles/ghost-for-cloudfoundry.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [ci/ci_image/*]

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/ghost-for-cloudfoundry-pipeline
