---
meta:
  name:    blog-starkandwayne
  team:    starkandwayne
  # fly -t ohio-sw login -c https://ci2.starkandwayne.com -n starkandwayne
  target:  ohio-sw
  url:     https://ci2.starkandwayne.com

  github:
    owner:  starkandwayne
    repo:   ghost-for-cloudfoundry
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  cf:
    api:              https://api.run.pivotal.io
    skip_cert_check:  false
    username:         ((pws-cf-username))
    password:         ((pws-cf-password))
    appname:          ghost
    organization:     starkandwayne
    spaces:
      staging:        blog-staging
      production:     blog-production

  slack:
    webhook:  ((slack-webhook))
    icon:     ((slack-logo))
    username: ((slack-username))
    channel:  "#snw-pws-apps"
